TomoBay: ServerStatus Class Reference
ServerStatus Class Reference
Copyright(C) 2015 Jan P.C.
Classes
enum RunLevel
enum providing allowed ServerStatus values
Public Member Functions
synchronized void setStatus (ServerStatus.RunLevel status)
allows a part of the system to set the status of the server.
Static Public Member Functions
static ServerStatus instance ()
retrieve an instance of this object
static synchronized ServerStatus.RunLevel getStatus ()
Allows a part of the system to query the current status of the server.
static String os ()
returns the name of the os that the server is being run on.
Private Member Functions
ServerStatus ()
private constructor ensures singleton is never instantiated
Static Private Attributes
static final ServerStatus instance_M = new ServerStatus()
singleton instance variable
static RunLevel status_M
status variable
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. This class represents the status of the server (surprise surprise) and provides functionality to get/set the status of the server.
The purpose of this is to allow other parts of the system to set the status of the server so that different modules can react differently given different server settings.
This class is a singleton which uses eager instantiaion to make it threadsafe. The setStatus and getStatus methods are synchronised for the same reason.
Author
Jan P.C. Hanson
Definition at line 31 of file ServerStatus.java.
Constructor & Destructor Documentation
ServerStatus () private
private constructor ensures singleton is never instantiated
Definition at line 43 of file ServerStatus.java.
Member Function Documentation
static ServerStatus instance () static
retrieve an instance of this object
Returns
ServerStatus
Definition at line 50 of file ServerStatus.java.
References ServerStatus.instance_M.
Referenced by PeriodicServicesController.executeStatic(), and MAIN.main().
synchronized void setStatus (ServerStatus.RunLevel status)
allows a part of the system to set the status of the server.
This method is synchronised to ensure threadsafety
Parameters
status defined by the ServerStatus.RunLevel enum
Definition at line 58 of file ServerStatus.java.
References ServerStatus.status_M.
Referenced by PeriodicServicesController.executeStatic(), and MAIN.main().
static synchronized ServerStatus.RunLevel getStatus () static
Allows a part of the system to query the current status of the server.
This method is synchronised to ensure threadsafety.
Returns
ServerStatus.Runlevel enum constant
Definition at line 66 of file ServerStatus.java.
References ServerStatus.status_M.
Referenced by AbstractService.call(), SalesOrderView.pickeability(), and SalesOrderPresenter.present().
static String os () static
returns the name of the os that the server is being run on.
Returns
String containing the os name.
Definition at line 73 of file ServerStatus.java.
Referenced by Part.badChar().
Member Data Documentation
final ServerStatus instance_M = new ServerStatus() static private
singleton instance variable
Definition at line 34 of file ServerStatus.java.
Referenced by ServerStatus.instance().
RunLevel status_M static private
status variable
Definition at line 36 of file ServerStatus.java.
Referenced by ServerStatus.getStatus(), and ServerStatus.setStatus().
The documentation for this class was generated from the following file:
/home/orpheus/Projects/Personal/Java/TomoBay/TomoGradle/src/main/java/com/tomoparts/tomoBay/model/dataTypes/ServerStatus.java