TomoBay: EmailDirector Class Reference
EmailDirector Class Reference
Copyright(C) 2015 Jan P.C.
Public Member Functions
EmailDirector () throws NoSuchProviderException
default ctor
void constructEmailAndServer (AbstractEmailBuilder builder)
initialises the email and server objects ready to be retrieved by the get methods.
Email getEmail () throws NullEmailObjectException
returns the email object after it has been initialised using the builder provided to the constructEmailAndServer method.
MailServerSend getMailSendServer () throws NullEmailServerObjectException
Provides functionality to access a MailServerSend object, which allows the sending of an Email.
Package Attributes
AbstractEmailBuilder builder_M
holder for the builder that determines the specific email server to connect to
Detailed Description
Copyright(C) 2015 Jan P.C.
Hanson & Tomo Motor Parts Limited
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/. This class is responsible for sending creating email and mail server objects. At the moment there is only a MailServerSend class but at some point it may be worth implementing a recieving interface as well.
In order to create email and server objects an AbstractEmailBuilder must be passed in. This builder determines the specifics of the email server that the system is to connect to.
Author
Jan P.C. Hanson
Definition at line 31 of file EmailDirector.java.
Constructor & Destructor Documentation
EmailDirector () throws NoSuchProviderException
default ctor
Exceptions
NoSuchProviderException
Definition at line 40 of file EmailDirector.java.
Member Function Documentation
void constructEmailAndServer (AbstractEmailBuilder builder)
initialises the email and server objects ready to be retrieved by the get methods.
Definition at line 46 of file EmailDirector.java.
References AbstractEmailBuilder.buildEmail(), and AbstractEmailBuilder.buildMailServerSendConnection().
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), EmailTest.main(), and MailClient.send().
Email getEmail () throws NullEmailObjectException
returns the email object after it has been initialised using the builder provided to the constructEmailAndServer method.
if no builder has been provided to this object then a NullEmailObjectException is thrown.
Returns
Email and fully initialised Email object
Exceptions
NullEmailObjectException Exception that means that no builder object has been provided to the EmailDirector before this method was called
Definition at line 61 of file EmailDirector.java.
References AbstractEmailBuilder.email_M.
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), and EmailTest.main().
MailServerSend getMailSendServer () throws NullEmailServerObjectException
Provides functionality to access a MailServerSend object, which allows the sending of an Email.
Returns
MailServerSend used to send emails
Exceptions
NullEmailServerObjectException indicates that no mailServer
Definition at line 74 of file EmailDirector.java.
References AbstractEmailBuilder.mailServer_M.
Referenced by EmailErrorsMailActions.EmailErrorsMailActions(), EmailTest.main(), and MailClient.send().
Member Data Documentation
AbstractEmailBuilder builder_M package
holder for the builder that determines the specific email server to connect to
Definition at line 34 of file EmailDirector.java.
The documentation for this class was generated from the following file:
/home/orpheus/Projects/Personal/Java/TomoBay/TomoGradle/src/main/java/com/tomoparts/tomoBay/model/net/email/EmailDirector.java