TomoBay: External.Files Enum Reference
External.Files Enum Reference
Public Member Functions
String get ()
Public Attributes
CONFIG_NAME =("tomoBay.conf")
the name of the config file
CONFIG_PATH =(PROJ_ROOT+"|config|")
the path to the directory of the config file
CONFIG_FULL =(PROJ_ROOT+"|config|tomoBay.conf")
the absolute path to the config file
ROYAL_MAIL_CSV_NAME =("RoyalMail.csv")
the name of the royal mail csv file
ROYAL_MAIL_CSV_PATH =(PROJ_ROOT+"|views|resources|")
the path to the directory of the royal mail csv file
ROYAL_MAIL_CSV_FULL =(PROJ_ROOT+"|views|resources|RoyalMail.csv")
the absolute path to the royal mail csv file
JETTY_SSL_CERT_NAME =("tomobay")
the name of the SSL certificate used by jetty
JETTY_SSL_KEYSTORE =(PROJ_ROOT+"|keystore|keystore.jks")
the absolute path to the java keystore that holds the SSL certificates
WEB_CLIENT_PATH =(PROJ_ROOT+"|views|")
path to the directory holding the web client
PUBLIC_API_ENDPOINT =("/res/*")
path of the tomobay public API endpoint
RETARD_API_ENDPOINT =("/retard/*")
path of unsecured API endpoint
Private Member Functions
Files (String file)
private constructor allows access to the parenthetical value for the current enum const
Private Attributes
final String file_M
holder for current instance name
Static Private Attributes
staticfinal String SEP = File.separator
the cross platform file seperator
Detailed Description
Author
Jan P.C. Hanson
Definition at line 38 of file External.java.
Constructor & Destructor Documentation
Files (String file) private
private constructor allows access to the parenthetical value for the current enum const
Parameters
file the name of the enum const
Definition at line 77 of file External.java.
Member Function Documentation
String get ()
Returns
the String value of the current enum const
Definition at line 83 of file External.java.
Member Data Documentation
CONFIG_NAME =("tomoBay.conf")
the name of the config file
Definition at line 41 of file External.java.
CONFIG_PATH =(PROJ_ROOT+"|config|")
the path to the directory of the config file
Definition at line 43 of file External.java.
CONFIG_FULL =(PROJ_ROOT+"|config|tomoBay.conf")
the absolute path to the config file
Definition at line 45 of file External.java.
ROYAL_MAIL_CSV_NAME =("RoyalMail.csv")
the name of the royal mail csv file
Definition at line 48 of file External.java.
Referenced by GenerateRoyalMailCSV.createCSV(), and RoyalMailCSVGeneratorTest.testGenerate().
ROYAL_MAIL_CSV_PATH =(PROJ_ROOT+"|views|resources|")
the path to the directory of the royal mail csv file
Definition at line 50 of file External.java.
Referenced by GenerateRoyalMailCSV.createCSV(), and RoyalMailCSVGeneratorTest.testGenerate().
ROYAL_MAIL_CSV_FULL =(PROJ_ROOT+"|views|resources|RoyalMail.csv")
the absolute path to the royal mail csv file
Definition at line 52 of file External.java.
Referenced by RoyalMailCSVGeneratorTest.testGenerate().
JETTY_SSL_CERT_NAME =("tomobay")
the name of the SSL certificate used by jetty
Definition at line 55 of file External.java.
Referenced by HttpServer.sslConnector().
JETTY_SSL_KEYSTORE =(PROJ_ROOT+"|keystore|keystore.jks")
the absolute path to the java keystore that holds the SSL certificates
Definition at line 57 of file External.java.
Referenced by HttpServer.sslConnector().
WEB_CLIENT_PATH =(PROJ_ROOT+"|views|")
path to the directory holding the web client
Definition at line 60 of file External.java.
Referenced by HttpServer.setUpGuiHandler().
PUBLIC_API_ENDPOINT =("/res/*")
path of the tomobay public API endpoint
Definition at line 62 of file External.java.
Referenced by HttpServer.setUpDataServletHandler().
RETARD_API_ENDPOINT =("/retard/*")
path of unsecured API endpoint
Definition at line 65 of file External.java.
Referenced by HttpServer.setUpUnsecuredServlet().
final String file_M private
holder for current instance name
Definition at line 69 of file External.java.
static final String SEP = File.separator static private
the cross platform file seperator
Definition at line 72 of file External.java.
The documentation for this enum was generated from the following file:
/home/orpheus/Projects/Personal/Java/TomoBay/TomoGradle/src/main/java/com/tomoparts/tomoBay/External.java